#!/bin/sh
# utility script to run scapy server locally

# usage ./run_scapy_server -v --scapy-port 4507

REPO=https://github.com/hedjuo/trex-core.git
TARGET=/tmp

[ -z "$PYTHON" ] && PYTHON=python

if [ -e $TARGET/trex-core ]; then
    cd $TARGET/trex-core
    git reset --hard > /dev/null
    git pull
else
    git clone --depth=1 $REPO $TARGET/trex-core
fi

cd $TARGET/trex-core/scripts/automation/trex_control_plane/stl/services/scapy_server

if [ "Darwin" = `uname` ]; then
    echo "Patching trex scapy server for Mac's native zmq"
    sed -i bak '/pyzmq.*arch-dep/d' $TARGET/trex-core/scripts/automation/trex_control_plane/stl/trex_stl_lib/trex_stl_ext.py
fi

echo "Running scapy server"
echo "$PYTHON scapy_zmq_server.py $@"
exec $PYTHON scapy_zmq_server.py $@

